.pragma library
// Spanish UI text for Control Deck: keys are the English strings of shell.qml (and the
// fixed sentences the backend shows), exactly. Missing keys fall back to English.
var ES = {
    "  Proton was changed for a run: RESTORE PROTON when done.": "  Se cambió el Proton para una prueba: pulsa RESTAURAR PROTON al terminar.",
    "  ·  Proton: ": "  ·  Proton: ",
    "  ·  data ": "  ·  datos ",
    "  ·  last ": "  ·  última ",
    "  ·  last driver update ": "  ·  última actualización del driver ",
    "  ·  menu ": "  ·  menú ",
    "  ·  on/off ": "  ·  on/off ",
    "  ·  since ": "  ·  desde ",
    "  ·  updated ": "  ·  actualizado ",
    "  ·  used ": "  ·  usado ",
    "  · default profile": "  · perfil por defecto",
    "  —  nothing is changed from here: copy the command and run it in a terminal": "  —  desde aquí no se cambia nada: copia el comando y ejecútalo en una terminal",
    " (newest)": " (más reciente)",
    " (no upgrades: GE-Proton or Proton-CachyOS do)": " (sin mejoras: GE-Proton o Proton-CachyOS sí las tienen)",
    " (set automatically)": " (se ajusta solo)",
    " (supports upgrades)": " (admite mejoras)",
    " APPS": " APPS",
    " Arch news since your last upgrade — some need manual steps. Read them before updating:": " noticias de Arch desde tu última actualización; algunas requieren pasos manuales. Léelas antes de actualizar:",
    " DLL. SAVE to apply.": " DLL. GUARDAR para aplicar.",
    " FILE": " ARCHIVO",
    " FILES": " ARCHIVOS",
    " GAME(S)…": " JUEGO(S)…",
    " GAMES": " JUEGOS",
    " GPU or aren't set up here yet": " o aún no están configurados en este PC",
    " Its guide, mapped to the deck, is under SAVED below.": " Su guía, adaptada a la app, está abajo en GUARDADOS.",
    " Its menu: INSERT (Page Down if INSERT is your shader key).": " Su menú: INSERT (Av Pág si INSERT es tu tecla de shaders).",
    " MORE ▾": " MÁS ▾",
    " PENDING": " PENDIENTES",
    " Proton builds available": " versiones de Proton disponibles",
    " READY": " LISTOS",
    " RESULTS": " RESULTADOS",
    " SNAPSHOTS": " SNAPSHOTS",
    " Shaders come from the packages the official ReShade installer lists.": " Los shaders vienen de los paquetes que lista el instalador oficial de ReShade.",
    " Space limits need Btrfs quotas (off).": " Los límites de espacio necesitan cuotas de Btrfs (desactivadas).",
    " TO CLEAN": " PARA LIMPIAR",
    " This game has FSR 3.1: the plain FSR 4 chip is simpler.": " Este juego trae FSR 3.1: el chip FSR 4 normal es más sencillo.",
    " backups in ~/control-deck-backups/prefixes": " copias en ~/control-deck-backups/prefixes",
    " belong to games that are no longer installed.": " son de juegos que ya no están instalados.",
    " can be cleaned (SHADERS)": " se pueden limpiar (SHADERS)",
    " downloads)": " descargas)",
    " effect": " efecto",
    " effects)": " efectos)",
    " file(s) can't be installed and will be skipped (rpm / deb without debtap / unknown).": " archivo(s) no se pueden instalar y se omitirán (rpm / deb sin debtap / desconocido).",
    " free of ": " libres de ",
    " from reshade.me, d3dcompiler_47 (Mozilla's Firefox installer, checksum-verified, like winetricks) and the standard shaders.": " desde reshade.me, d3dcompiler_47 (del instalador de Firefox de Mozilla, verificado, como winetricks) y los shaders estándar.",
    " important), none younger than ": " importantes), ninguno más reciente que ",
    " in orphans (no game uses them)": " en huérfanos (ningún juego los usa)",
    " is ": " es ",
    " is out (you have ": " ya está disponible (tienes la ",
    " min played": " min jugados",
    " numbered snapshots (": " snapshots numerados (",
    " of 5 done — next: ": " de 5 hechos — siguiente: ",
    " of driver caches weren't used since the last driver update: they are stale. ": " de cachés del driver no se han usado desde la última actualización del driver: están obsoletas. ",
    " opens ReShade's menu — tweak values, switch effects on/off; changes are saved to this game's preset.": " abre el menú de ReShade: ajusta valores y activa o desactiva efectos; los cambios se guardan en el preset de este juego.",
    " orphan(s) (PREFIXES)": " huérfano(s) (PREFIXES)",
    " players": " jugadores",
    " prefixes · ": " prefixes · ",
    " presets in this file: pick one": " presets en este archivo: elige uno",
    " presets · best: ": " presets · el mejor: ",
    " presets — newest first": " presets — los más nuevos primero",
    " problem": " problema",
    " problem(s)": " problema(s)",
    " reports ↗": " informes ↗",
    " reports)": " informes)",
    " risk": " riesgo",
    " setting(s) don't fit this ": " ajuste(s) no encajan con esta GPU ",
    " shader file(s) from the archive": " archivo(s) de shader del archivo descargado",
    " similar players": " jugadores similares",
    " skipped": " omitidos",
    " switches all effects on/off. ": " activa o desactiva todos los efectos. ",
    " threads · ": " hilos · ",
    " through the deck · ": " por la app · ",
    " to set up": " por configurar",
    " turns the effects on/off to compare.": " activa o desactiva los efectos para comparar.",
    " uses ": ") usa ",
    " votes": " votos",
    " warning": " aviso",
    " warning(s)": " aviso(s)",
    " who say it works use it (": " que dicen que funciona lo usan (",
    " with shaders": " con shaders",
    " · active": " · activo",
    " · confidence ": " · confianza ",
    " · depth: ": " · profundidad: ",
    " · idle": " · en reposo",
    " · trending ": " · tendencia ",
    " · you =": " · tú =",
    " — in vkBasalt, effects that need the depth buffer are skipped": " — en vkBasalt se omiten los efectos que necesitan el buffer de profundidad",
    " — open it, download the file, then IMPORT…": " — ábrelo, descarga el archivo y pulsa IMPORTAR…",
    " — right-click removes it": " — clic derecho para quitarlo",
    " → NOW": " → AHORA",
    "% leave it at the default": "% lo dejan por defecto",
    "% of ": "% de ",
    "' config on this system: nothing to show.": "' en este sistema: no hay nada que mostrar.",
    "). Every game's shader cache gets rebuilt: expect some stutter the first time you play each game. Old driver caches can be cleaned afterwards in GAMING → SHADERS.": "). La caché de shaders de cada juego se reconstruye: habrá algún tirón la primera vez que juegues a cada uno. Las cachés viejas del driver se pueden limpiar después en GAMING → SHADERS.",
    "). Games pick it up on their next launch.": "). Los juegos la usan en su próximo arranque.",
    "). Shaders hook into the game's rendering; an anti-cheat may treat that as a modification and ban the account. Use them only if you accept that risk — applying one here asks for confirmation.": "). Los shaders se enganchan al render del juego; un anti-cheat puede tomarlo como una modificación y banear la cuenta. Úsalos solo si aceptas ese riesgo: aplicar uno aquí pide confirmación.",
    "): not touched": "): no se toca",
    "+ DELETE DATA": "+ BORRAR DATOS",
    "+ LINK": "+ ENLACE",
    ", which ignores the level (only BFQ honours it).": ", que ignora el nivel (solo BFQ lo respeta).",
    "-only → remove": " solamente → quitar",
    ". Already in the profile.": ". Ya está en el perfil.",
    ". Change it any time below.": ". Cámbialo cuando quieras abajo.",
    ". Click to add, then SAVE.": ". Pulsa para añadir y luego GUARDAR.",
    ". Click to open.": ". Pulsa para abrir.",
    ". Shaders: the packages the official ReShade installer lists.": ". Shaders: los paquetes que lista el instalador oficial de ReShade.",
    ".deb  (with debtap)": ".deb  (con debtap)",
    ".dll + d3dcompiler_47 linked in the game folder · OFF removes them": ".dll + d3dcompiler_47 enlazados en la carpeta del juego · OFF los quita",
    "// log output": "// registro",
    "/mo": "/mes",
    "0.1% low": "0,1% mínimo",
    "1% low": "1% mínimo",
    "100+ votes on the AUR": "Más de 100 votos en el AUR",
    "2D game drawn with GDI (RPG Maker style): no shader tool can hook it.": "Juego 2D dibujado con GDI (estilo RPG Maker): ninguna herramienta de shaders puede engancharse.",
    "32-BIT LIBRARIES": "LIBRERÍAS DE 32 BITS",
    "32-bit TLS (online games)": "TLS de 32 bits (juegos online)",
    "32-bit audio": "audio de 32 bits",
    ": ReShade's menu, tick/untick effects and move sliders (saved to this game). ": ": menú de ReShade; marca o desmarca efectos y mueve los controles (se guarda en este juego). ",
    ": keeps ": ": guarda ",
    "; in vkBasalt, effects that need the depth buffer are skipped.": "; en vkBasalt se omiten los efectos que necesitan el buffer de profundidad.",
    "; value adapted to this PC": "; valor adaptado a este PC",
    "A CPU · GPU temperature line at the top right while the game runs (click-through, closes with the game)": "Una línea con la temperatura de CPU y GPU arriba a la derecha mientras juegas (no bloquea el ratón y se cierra con el juego)",
    "A Vulkan layer: simplest, no files in the game folder; presets are converted and effects that need depth are skipped.": "Una capa de Vulkan: lo más sencillo, sin archivos en la carpeta del juego; los presets se convierten y se omiten los efectos de profundidad.",
    "A polkit rule so your user switches schedulers without a password (needed for WHILE PLAYING without prompts)": "Una regla de polkit para que tu usuario cambie de planificador sin contraseña (necesaria para MIENTRAS JUEGAS sin avisos)",
    "A preset you downloaded (Nexus Mods…): zip, 7z, rar or .ini. Its own shaders come along; its ReShade.ini/DLLs are ignored.": "Un preset que hayas descargado (Nexus Mods…): zip, 7z, rar o .ini. Sus shaders se instalan con él; su ReShade.ini y sus DLL se ignoran.",
    "A repository that isn't Arch's or CachyOS's": "Un repositorio que no es de Arch ni de CachyOS",
    "A/B BENCHMARKS ARE FOR STEAM GAMES": "LAS PRUEBAS A/B SON PARA JUEGOS DE STEAM",
    "ACTIVE ✓": "ACTIVO ✓",
    "ADJUSTING PROFILES…": "AJUSTANDO PERFILES…",
    "AFTER": "DESPUÉS",
    "ALL CLEAN ✓": "TODO LIMPIO ✓",
    "ALL MISSING": "TODO LO QUE FALTA",
    "ALL UP TO DATE ✓": "TODO AL DÍA ✓",
    "ALL": "TODO",
    "ALLOW MY USER": "PERMITIR A MI USUARIO",
    "ALLOWING…": "PERMITIENDO…",
    "AMD FidelityFX CAS: crisper image, almost free": "AMD FidelityFX CAS: imagen más nítida, casi gratis",
    "ANALYZING…": "ANALIZANDO…",
    "APPLY": "APLICAR",
    "APPLYING PRESET…": "APLICANDO PRESET…",
    "APPLYING…": "APLICANDO…",
    "APPS DIR": "CARPETA APPS",
    "AS IS": "TAL CUAL",
    "AT BOOT": "AL ARRANCAR",
    "AUR cache": "Caché de AUR",
    "AUR votes: users who vouch for the package": "Votos en el AUR: usuarios que respaldan el paquete",
    "AUTO-CHECK OFF": "COMPROBACIÓN AUTO OFF",
    "AUTOSTART": "INICIO AUTOMÁTICO",
    "AWAITING FILE": "ESPERANDO ARCHIVO",
    "Active: ": "Activo: ",
    "Arch doesn't support partial upgrades: repo packages are updated together (pacman -Syu). AUR opens a terminal.": "Arch no admite actualizaciones parciales: los paquetes de los repos se actualizan juntos (pacman -Syu). AUR abre una terminal.",
    "Auto-cleanup ": "Limpieza automática ",
    "Avg FPS": "FPS medio",
    "BACKING UP + DELETING…": "COPIANDO + BORRANDO…",
    "BACKING UP…": "HACIENDO COPIA…",
    "BACKUP": "COPIA",
    "BACKUPS ↗": "COPIAS ↗",
    "BENCH": "PRUEBAS",
    "BUILD & INSTALL": "COMPILAR E INSTALAR",
    "BUILD ANYWAY": "COMPILAR IGUALMENTE",
    "Back to the kernel's scheduler (asks for your password)": "Vuelve al planificador del kernel (pide tu contraseña)",
    "Battle.net client": "Cliente de Battle.net",
    "Battle.net game": "Juego de Battle.net",
    "Below: a QUICK LOOK, a SweetFX DB preset (APPLY), or one from Nexus: SEARCH NEXUS → download it → IMPORT…": "Abajo: un LOOK RÁPIDO, un preset de SweetFX DB (APLICAR) o uno de Nexus: BUSCAR EN NEXUS → descárgalo → IMPORTAR…",
    "Broken launchers": "Lanzadores rotos",
    "Building runs the PKGBUILD on your machine. Read it if anything is flagged.": "Compilar ejecuta el PKGBUILD en tu equipo. Léelo si se ha marcado algo.",
    "Built-in look": "Look integrado",
    "CANCEL": "CANCELAR",
    "CHECK FOR THIS PC — ": "REVISAR PARA ESTE PC — ",
    "CHECK FOR THIS PC": "REVISAR PARA ESTE PC",
    "CHECK": "COMPROBAR",
    "CHECKING FOR UPDATES…": "BUSCANDO ACTUALIZACIONES…",
    "CHECKING": "COMPROBANDO",
    "CHECKING…": "COMPROBANDO…",
    "CLARITY": "CLARIDAD",
    "CLEAN ORPHANS": "LIMPIAR HUÉRFANOS",
    "CLEAN STALE": "LIMPIAR OBSOLETAS",
    "CLEAN": "LIMPIAR",
    "CLEANING UP…": "LIMPIANDO…",
    "CLEANING…": "LIMPIANDO…",
    "CLEANUP NOW": "LIMPIAR AHORA",
    "CLEAR": "BORRAR",
    "CLEARING…": "BORRANDO…",
    "CLICK AGAIN TO CONFIRM": "PULSA OTRA VEZ PARA CONFIRMAR",
    "CLOCK": "FRECUENCIA",
    "CLONE": "CLONAR",
    "CLONING…": "CLONANDO…",
    "CLOSE STEAM FIRST": "CIERRA STEAM ANTES",
    "CLOSING…": "CERRANDO…",
    "COMPARING…": "COMPARANDO…",
    "CONFIRM ": "CONFIRMAR ",
    "CONFIRM?": "¿CONFIRMAR?",
    "COPIED ✓": "COPIADO ✓",
    "COPY": "COPIAR",
    "CPU load %": "Carga de CPU %",
    "CPU · GPU temperature line at the top right while the game runs": "Línea de temperatura de CPU y GPU arriba a la derecha mientras juegas",
    "CPU · MEMORY": "CPU · MEMORIA",
    "CREATE": "CREAR",
    "Checked every 6 h in the background: you get a notification, even with the deck closed.": "Se comprueba cada 6 h en segundo plano: recibes una notificación aunque la app esté cerrada.",
    "Choose a Control Deck backup (.json)": "Elige una copia de Control Deck (.json)",
    "Choose a downloaded ReShade preset": "Elige un preset de ReShade descargado",
    "Choose an icon": "Elige un icono",
    "Click to add, then SAVE · % of players who say it works · ProtonDB (ODbL) ": "Pulsa para añadir y luego GUARDAR · % de jugadores que dicen que funciona · ProtonDB (ODbL) ",
    "Close Steam, then USE IN STEAM.": "Cierra Steam y pulsa USAR EN STEAM.",
    "Close Steam, then press USE IN STEAM.": "Cierra Steam y pulsa USAR EN STEAM.",
    "Control Deck downloads": "Descargas de Control Deck",
    "DELETE (": "BORRAR (",
    "DELETE always makes a backup first (a Steam game's prefix is recreated on its next launch — saves kept only in the prefix would be lost without it). CLONE copies the Wine prefix to ~/Games/prefixes (instant on Btrfs). Restore a backup: control-deck prefix restore <backup> <folder>.": "BORRAR siempre hace antes una copia (el prefix de un juego de Steam se recrea al lanzarlo y sin ella se perderían las partidas guardadas solo en el prefix). CLONAR copia el prefix de Wine a ~/Games/prefixes (instantáneo en Btrfs). Restaurar una copia: control-deck prefix restore <copia> <carpeta>.",
    "DELETE": "BORRAR",
    "DELETING…": "BORRANDO…",
    "DIFF → NOW": "DIFF → AHORA",
    "DISK ": "DISCO ",
    "DLSS (newest)": "DLSS (más reciente)",
    "DLSS needs an NVIDIA RTX card.": "DLSS necesita una tarjeta NVIDIA RTX.",
    "DONE WITH ERRORS": "TERMINADO CON ERRORES",
    "DONE ✓": "HECHO ✓",
    "DOWNLOAD FAILED": "FALLÓ LA DESCARGA",
    "DOWNLOADING RESHADE…": "DESCARGANDO RESHADE…",
    "DOWNLOADING…": "DESCARGANDO…",
    "DRIVER CACHE": "CACHÉ DEL DRIVER",
    "DRIVER": "DRIVER",
    "DROP PACKAGE(S) HERE": "SUELTA AQUÍ LOS PAQUETES",
    "Denoised luma sharpening: detail without boosting grain": "Nitidez de luminancia sin ruido: detalle sin aumentar el grano",
    "Dependencies no package needs any more (pacman -Rns).": "Dependencias que ya no necesita ningún paquete (pacman -Rns).",
    "Do Not Disturb in swaync while you play; notifications wait in its panel": "No molestar en swaync mientras juegas; las notificaciones esperan en su panel",
    "Download it and fetch the shaders it needs; ReShade runs it as it is": "Lo descarga y baja los shaders que necesita; ReShade lo usa tal cual",
    "Download, fetch the shaders it needs and convert it for vkBasalt": "Lo descarga, baja los shaders que necesita y lo convierte para vkBasalt",
    "Downloaded from reshade.me into your user folder, no password.": "Se descarga de reshade.me a tu carpeta de usuario, sin contraseña.",
    "Driver caches older than the last driver update, and caches of uninstalled games (rebuilt when needed).": "Cachés del driver anteriores a su última actualización y cachés de juegos desinstalados (se rehacen cuando hace falta).",
    "Drivers: ": "Drivers: ",
    "EDIT": "EDITAR",
    "EXECUTABLE": "EJECUTABLE",
    "EXPORT BACKUP": "EXPORTAR COPIA",
    "EXPORT": "EXPORTAR",
    "EXPORTING…": "EXPORTANDO…",
    "Every Steam game: the most downloaded ReShade preset on SweetFX Settings DB, the ReShade compatibility list (PCGamingWiki, which reshade.me links) and online/anti-cheat risk. SET UP installs ReShade with that preset — or SHARPEN + AA when there's none — and the depth settings the list gives. Anti-cheat games and games where ReShade is banned are never touched.": "Cada juego de Steam: el preset de ReShade más descargado de SweetFX Settings DB, la lista de compatibilidad de ReShade (PCGamingWiki, la que enlaza reshade.me) y el riesgo online o de anti-cheat. CONFIGURAR instala ReShade con ese preset (o NITIDEZ + AA si no hay ninguno) y los ajustes de profundidad de la lista. Los juegos con anti-cheat o donde ReShade está vetado nunca se tocan.",
    "Every step, with what each one does": "Todos los pasos, con lo que hace cada uno",
    "Executable, graphics API and the in-game keys": "Ejecutable, API gráfica y teclas en el juego",
    "FAILED · ": "FALLÓ · ",
    "FEW VOTES": "POCOS VOTOS",
    "FILE": "ARCHIVO",
    "FIX ALL": "ARREGLAR TODO",
    "FIX FAILED": "NO SE PUDO ARREGLAR",
    "FIXED ✓": "ARREGLADO ✓",
    "FIXING…": "ARREGLANDO…",
    "FOLDER ↗": "CARPETA ↗",
    "FOLDER": "CARPETA",
    "FPS LIMIT": "LÍMITE FPS",
    "FROM A FILE": "DESDE ARCHIVO",
    "FSR 4 needs a Radeon RX 9000 (RDNA4) or RX 7000 with GE-Proton.": "FSR 4 necesita una Radeon RX 9000 (RDNA4) o una RX 7000 con GE-Proton.",
    "FSR 4 runs on AMD Radeon RX 9000 (RDNA4) — not on this GPU.": "FSR 4 funciona en AMD Radeon RX 9000 (RDNA4), no en esta GPU.",
    "FSR 4 through OptiScaler is offered on Radeon RX 9000 (RDNA4).": "FSR 4 con OptiScaler se ofrece en Radeon RX 9000 (RDNA4).",
    "FSR 4 via OptiScaler": "FSR 4 vía OptiScaler",
    "Files downloaded from GitHub/URLs.": "Archivos descargados de GitHub o URLs.",
    "Flagged out of date on the AUR": "Marcado como desactualizado en el AUR",
    "Flathub installs last month": "Instalaciones en Flathub el último mes",
    "Flathub verified the developer: it comes from the app's own authors": "Flathub verificó al desarrollador: viene de los propios autores de la app",
    "Frames": "Fotogramas",
    "From SweetFX Settings DB (sfx.thelazy.net), made for ReShade": "De SweetFX Settings DB (sfx.thelazy.net), hechos para ReShade",
    "From SweetFX Settings DB": "De SweetFX Settings DB",
    "From chaotic-aur (asks for your password) plus the standard shaders.": "Desde chaotic-aur (pide tu contraseña) y los shaders estándar.",
    "GAME": "JUEGO",
    "GAMING ONLY": "SOLO GAMING",
    "GAMING TOOLS": "HERRAMIENTAS",
    "GET DATA (70 MB)": "DESCARGAR DATOS (70 MB)",
    "GPU DRIVER": "DRIVER DE GPU",
    "GPU LOAD": "CARGA GPU",
    "GPU load %": "Carga de GPU %",
    "GPU max °C": "GPU máx °C",
    "GUIDE ▴": "GUÍA ▴",
    "GUIDE ▾": "GUÍA ▾",
    "GameMode active": "GameMode activo",
    "GameMode has it on performance": "GameMode lo tiene en rendimiento",
    "GameMode switches it to performance while you play": "GameMode lo pone en rendimiento mientras juegas",
    "Games launched through the deck (Steam) or Umbral 0.10+.": "Juegos lanzados con la app (Steam) o con Umbral 0.10+.",
    "Get the data once to see what players with hardware like yours use.": "Descarga los datos una vez para ver qué usan los jugadores con un hardware como el tuyo.",
    "HEALTH →": "SALUD →",
    "HEALTH": "SALUD",
    "HELD BACK BY": "LIMITADA POR",
    "HIDDEN": "OCULTO",
    "HISTORY": "HISTORIAL",
    "HOLD NOTIFICATIONS": "RETENER NOTIFICACIONES",
    "Has online modes without anti-cheat: fine for single-player; check the game's rules online.": "Tiene modos online sin anti-cheat: bien para un jugador; revisa las normas del juego online.",
    "Hyprland animations, blur and shadows off while you play, back as they were after": "Animaciones, desenfoque y sombras de Hyprland apagados mientras juegas; después vuelven como estaban",
    "Hyprland/HyDE and most desktops take PrtSc for their own screenshots: then the game never gets it": "Hyprland/HyDE y la mayoría de escritorios usan Impr Pant para sus propias capturas: entonces el juego nunca la recibe",
    "IMPORTING PRESET…": "IMPORTANDO PRESET…",
    "IMPORTING…": "IMPORTANDO…",
    "IMPORT…": "IMPORTAR…",
    "IN USE": "EN USO",
    "INDEXING PROTONDB DATA…": "INDEXANDO DATOS DE PROTONDB…",
    "INSTALL ": "INSTALAR ",
    "INSTALL ALL": "INSTALAR TODO",
    "INSTALL": "INSTALAR",
    "INSTALLED": "INSTALADO",
    "INSTALLING ": "INSTALANDO ",
    "INSTALLING SHADERS…": "INSTALANDO SHADERS…",
    "INSTALLING…": "INSTALANDO…",
    "IO PRIORITY": "PRIORIDAD E/S",
    "If you use one anyway, vkBasalt is the lighter touch: a Vulkan layer, no DLL or files in the game folder.": "Si aun así usas uno, vkBasalt es lo menos invasivo: una capa de Vulkan, sin DLL ni archivos en la carpeta del juego.",
    "Imported from ": "Importado de ",
    "Imported preset": "Preset importado",
    "In game: ": "En el juego: ",
    "Inherited from the prefix. Click to set it on this game.": "Heredado del prefix. Pulsa para fijarlo en este juego.",
    "Install ": "Instalar ",
    "Install ReShade next to this .exe (detected API: ": "Instalar ReShade junto a este .exe (API detectada: ",
    "Installed: the preset in use was imported from this mod's file.": "Instalado: el preset en uso se importó del archivo de este mod.",
    "Installs whatever is missing from a backup: repo packages with pacman, Flatpaks, GitHub AppImages and launchers. AUR packages are built in a terminal.": "Instala lo que falte de una copia: paquetes de los repos con pacman, Flatpaks, AppImages de GitHub y lanzadores. Los paquetes de AUR se compilan en una terminal.",
    "Its Steam launch options go through the deck, which loads the shaders.": "Sus opciones de lanzamiento de Steam pasan por la app, que carga los shaders.",
    "JOIN GROUP": "UNIRSE AL GRUPO",
    "JOINING…": "UNIÉNDOSE…",
    "Keep a preset page for this game": "Guardar una página de preset para este juego",
    "LAST SESSIONS": "ÚLTIMAS PARTIDAS",
    "LAUNCH FAILED ✗": "NO SE PUDO LANZAR ✗",
    "LAUNCH": "LANZAR",
    "LAUNCHING…": "LANZANDO…",
    "LAVD GAMING NOW": "LAVD GAMING YA",
    "LESS ▴": "MENOS ▴",
    "LIBRARY · STORAGE": "BIBLIOTECA · ALMACENAMIENTO",
    "LIBRARY": "BIBLIOTECA",
    "LIVE": "EN VIVO",
    "LOAD (PASSWORD)": "CARGAR (CONTRASEÑA)",
    "LOAD": "CARGA",
    "LOADING SNAPSHOTS…": "CARGANDO SNAPSHOTS…",
    "LOOKING FOR PREFIXES…": "BUSCANDO PREFIXES…",
    "Launch it from Umbral": "Lánzalo desde Umbral",
    "Launch it through Control Deck": "Lánzalo a través de Control Deck",
    "Launch options are set in Umbral. Control Deck adds TEMPS and shaders when Umbral 0.10.0+ starts the game.": "Las opciones de lanzamiento se configuran en Umbral. Control Deck añade TEMPS y shaders cuando Umbral 0.10.0+ arranca el juego.",
    "Launch the game and press ": "Lanza el juego y pulsa ",
    "Launch the game; ": "Lanza el juego; ",
    "Light anti-aliasing, softer edges": "Antialiasing ligero, bordes más suaves",
    "Loading presets…": "Cargando presets…",
    "MANAGE": "GESTIONAR",
    "MANGOHUD": "MANGOHUD",
    "MEASURE": "MEDIR",
    "MEASURING CACHES…": "MIDIENDO CACHÉS…",
    "MENU KEY": "TECLA MENÚ",
    "MORE ▾": "MÁS ▾",
    "MOVING RESHADE…": "MOVIENDO RESHADE…",
    "MY LIBRARY": "MI BIBLIOTECA",
    "Menu entries whose program no longer exists (moved to a trash folder).": "Entradas del menú cuyo programa ya no existe (se mueven a una papelera).",
    "Mesa + Intel Vulkan": "Mesa + Intel Vulkan",
    "Mesa + RADV Vulkan": "Mesa + RADV Vulkan",
    "NEW · FEW VOTES": "NUEVO · POCOS VOTOS",
    "NEW": "NUEVO",
    "NO ANIMATIONS / BLUR": "SIN ANIMACIONES / DESENFOQUE",
    "NO DATA": "SIN DATOS",
    "NO FILE": "SIN ARCHIVO",
    "NO GAMES FOUND": "NO SE ENCONTRARON JUEGOS",
    "NO OPERATIONS YET": "AÚN NO HAY OPERACIONES",
    "NO PASSWORD": "SIN CONTRASEÑA",
    "NO RESULTS FOR «": "SIN RESULTADOS PARA «",
    "NO RUNS YET": "AÚN NO HAY PRUEBAS",
    "NO SHADER CACHES": "NO HAY CACHÉS DE SHADERS",
    "NO SNAPSHOTS LOADED": "NO HAY SNAPSHOTS CARGADOS",
    "NO WINE/PROTON PREFIXES FOUND": "NO HAY PREFIXES DE WINE/PROTON",
    "NONE INSTALLABLE": "NADA INSTALABLE",
    "NONE": "NINGUNO",
    "NOT CHECKED": "SIN COMPROBAR",
    "NVIDIA kernel module": "módulo del kernel NVIDIA",
    "NVIDIA userspace": "NVIDIA (espacio de usuario)",
    "NVIDIA versions": "versiones de NVIDIA",
    "Native Linux build that draws with OpenGL: neither vkBasalt (Vulkan only) nor ReShade (Windows only) can hook it.": "Versión nativa de Linux que dibuja con OpenGL: ni vkBasalt (solo Vulkan) ni ReShade (solo Windows) pueden engancharse.",
    "Native Linux build that draws with Vulkan: vkBasalt is the only one that can hook it (ReShade needs a Windows game).": "Versión nativa de Linux que dibuja con Vulkan: vkBasalt es el único que puede engancharse (ReShade necesita un juego de Windows).",
    "Needs Umbral 0.10.0 or newer (it asks the deck before launching): update Umbral.": "Necesita Umbral 0.10.0 o posterior (pregunta a la app antes de lanzar): actualiza Umbral.",
    "Needs dunst or swaync running": "Necesita dunst o swaync en marcha",
    "No ProtonDB report with launch options for this game yet.": "Aún no hay informes de ProtonDB con opciones de lanzamiento para este juego.",
    "No ReShade preset in that file (it needs a Techniques= line).": "No hay ningún preset de ReShade en ese archivo (necesita una línea Techniques=).",
    "No ReShade presets on SweetFX DB → SET UP uses SHARPEN + AA": "No hay presets de ReShade en SweetFX DB → CONFIGURAR usa NITIDEZ + AA",
    "No effect here: this game's disk ": "Aquí no hace nada: el disco de este juego (",
    "No game with that name on SweetFX Settings DB: try another name, or use a quick look.": "No hay ningún juego con ese nombre en SweetFX Settings DB: prueba otro nombre o usa un look rápido.",
    "No key: effects stay on": "Sin tecla: los efectos quedan siempre activos",
    "No maintainer: nobody updates or checks it": "Sin mantenedor: nadie lo actualiza ni lo revisa",
    "No upscaler upgrade for this game ⓘ": "No hay mejoras de escalado para este juego ⓘ",
    "Nothing is used by enough similar players to recommend it. ": "Nada lo usan suficientes jugadores similares como para recomendarlo. ",
    "Nothing to clean in: ": "Nada que limpiar en: ",
    "OFFICIAL": "OFICIAL",
    "ON-SCREEN CHECK": "MARCA EN PANTALLA",
    "ON/OFF KEY": "TECLA ON/OFF",
    "OPEN ": "ABRIR ",
    "OPEN": "ABRIR",
    "OPENING…": "ABRIENDO…",
    "ORPHAN": "HUÉRFANO",
    "ORPHANED (no maintainer)": "HUÉRFANO (sin mantenedor)",
    "OUT OF DATE": "DESACTUALIZADO",
    "Official Arch / CachyOS repository: built and signed by the distribution": "Repositorio oficial de Arch / CachyOS: compilado y firmado por la distribución",
    "Old package versions (the latest one is kept: paccache -rk1).": "Versiones antiguas de paquetes (se guarda la última: paccache -rk1).",
    "One-time setup, no password: ReShade ": "Configuración inicial, sin contraseña: ReShade ",
    "One-time setup: vkBasalt (the Vulkan layer that draws the effects, 64 + 32-bit, from chaotic-aur) and the standard ReShade shaders (official packages, ~0.5 MB). Works the same on AMD and NVIDIA.": "Configuración inicial: vkBasalt (la capa de Vulkan que dibuja los efectos, 64 y 32 bits, desde chaotic-aur) y los shaders estándar de ReShade (paquetes oficiales, ~0,5 MB). Funciona igual en AMD y NVIDIA.",
    "Online game with anti-cheat: OptiScaler hooks the game, not worth a ban.": "Juego online con anti-cheat: OptiScaler se engancha al juego, no merece un baneo.",
    "Only change it if ReShade doesn't show up in game": "Cámbialo solo si ReShade no aparece en el juego",
    "Only on Hyprland": "Solo en Hyprland",
    "Open the folder with this game's preset": "Abre la carpeta con el preset de este juego",
    "Open the preset's page": "Abrir la página del preset",
    "OptiScaler needs the game to offer DLSS, XeSS or FSR 2/3.1 to take over — none found.": "OptiScaler necesita que el juego ofrezca DLSS, XeSS o FSR 2/3.1 para sustituirlo, y no trae ninguno.",
    "OptiScaler takes over the game's DLSS / XeSS / FSR and renders it with FSR 4 — pick that upscaler in the game's settings. Proton downloads everything; nothing to install.": "OptiScaler toma el DLSS / XeSS / FSR del juego y lo renderiza con FSR 4: elige ese escalado en las opciones del juego. Proton lo descarga todo; no hay que instalar nada.",
    "Orphan packages": "Paquetes huérfanos",
    "Orphan prefixes": "Prefixes huérfanos",
    "Own game": "Juego propio",
    "PERMS": "PERMISOS",
    "PICK A GAME IN LIBRARY FIRST": "ELIGE ANTES UN JUEGO EN BIBLIOTECA",
    "PICK A STEAM OR UMBRAL GAME IN LIBRARY": "ELIGE UN JUEGO DE STEAM O UMBRAL EN BIBLIOTECA",
    "POPULAR": "POPULAR",
    "POWER": "CONSUMO",
    "PREBUILT AUR": "AUR PRECOMPILADO",
    "PRESS CHECK": "PULSA COMPROBAR",
    "PRESS RESCAN": "PULSA VOLVER A ESCANEAR",
    "PRESS SCAN": "PULSA SCAN",
    "PROFILE": "PERFIL",
    "PRT SC": "IMPR PANT",
    "Pacman cache": "Caché de pacman",
    "Pauses dunst while you play; what arrived shows when the game closes": "Pausa dunst mientras juegas; lo que haya llegado aparece al cerrar el juego",
    "Pick a look": "Elige un look",
    "Play and tweak": "Juega y ajusta",
    "Players don't agree on any launch option for this game.": "Los jugadores no coinciden en ninguna opción de lanzamiento para este juego.",
    "Presets: SweetFX Settings DB (sfx.thelazy.net), made for ReShade": "Presets: SweetFX Settings DB (sfx.thelazy.net), hechos para ReShade",
    "Press USE IN STEAM.": "Pulsa USAR EN STEAM.",
    "Proton builds in compatibilitytools.d no Steam game, Umbral prefix or running game uses.": "Versiones de Proton en compatibilitytools.d que no usa ningún juego de Steam, prefix de Umbral ni juego en marcha.",
    "Proton swaps in the newest ": "Proton pone la versión más reciente de ",
    "ProtonDB's open data (every game's reported launch options), indexed locally to ≈5 MB": "Datos abiertos de ProtonDB (las opciones de lanzamiento de cada juego), indexados en local en ≈5 MB",
    "ProtonDB: score ": "ProtonDB: puntuación ",
    "QUICK LOOK": "LOOK RÁPIDO",
    "RAM · VRAM %": "RAM · VRAM %",
    "READ THE ARCH NEWS FIRST · CLICK AGAIN": "LEE ANTES LAS NOTICIAS DE ARCH · PULSA OTRA VEZ",
    "READING THE PKGBUILD…": "LEYENDO EL PKGBUILD…",
    "READING YOUR LIBRARY…": "LEYENDO TU BIBLIOTECA…",
    "REALLY BUILD?": "¿COMPILAR DE VERDAD?",
    "RECENTLY PLAYED": "JUGADO RECIENTEMENTE",
    "RECHECK": "VOLVER A COMPROBAR",
    "REFRESH RESULTS": "ACTUALIZAR RESULTADOS",
    "REFRESH": "ACTUALIZAR",
    "REMOVED ✓": "QUITADO ✓",
    "REMOVING LINK…": "QUITANDO ENLACE…",
    "RESCAN": "VOLVER A ESCANEAR",
    "RESET": "RESTABLECER",
    "RESETTING…": "RESTABLECIENDO…",
    "RESTORE PROTON": "RESTAURAR PROTON",
    "RESTORE STEAM": "RESTAURAR STEAM",
    "RESTORE": "RESTAURAR",
    "RESTORING…": "RESTAURANDO…",
    "REVIEW AND CONFIRM": "REVISAR Y CONFIRMAR",
    "REVIEW FAILED": "FALLÓ LA REVISIÓN",
    "REVIEW": "REVISAR",
    "REVIEWING ": "REVISANDO ",
    "RISK: ": "RIESGO: ",
    "ROM (emulator)": "ROM (emulador)",
    "ROUTE": "VÍA",
    "RUN ": "PRUEBA ",
    "RUN A": "PROBAR A",
    "RUN B": "PROBAR B",
    "RUN starts the game from Steam; MangoHud records every frame after the delay, for the measured time. Play the same scene in both runs, quit the game, then REFRESH. Variants changing Proton need Steam closed.": "PROBAR A/B lanza el juego desde Steam; MangoHud registra cada fotograma tras la espera, durante el tiempo medido. Juega la misma escena en las dos pruebas, cierra el juego y pulsa ACTUALIZAR. Las variantes que cambian de Proton necesitan Steam cerrado.",
    "RUNNING NOW": "EN EJECUCIÓN",
    "RUNNING ▶": "EN MARCHA ▶",
    "RUNNING": "EN EJECUCIÓN",
    "RX 7000 (RDNA3) needs GE-Proton's RDNA3 variant.": "RX 7000 (RDNA3) necesita la variante RDNA3 de GE-Proton.",
    "ReShade isn't installed in its folder on this PC → set it up": "ReShade no está instalado en su carpeta en este PC → configúralo",
    "ReShade itself: presets exactly as made (depth effects too) and its in-game menu. For D3D9–12 and OpenGL games.": "ReShade de verdad: los presets tal cual se hicieron (con efectos de profundidad) y su menú en el juego. Para juegos D3D9–12 y OpenGL.",
    "ReShade not installed": "ReShade no instalado",
    "ReShade presets for this game on SweetFX DB — see GAMING → FX": "Presets de ReShade para este juego en SweetFX DB: mira GAMING → FX",
    "Reading ": "Leyendo ",
    "Recommended here: ": "Recomendado aquí: ",
    "Record each game session and notify a summary when it ends": "Registra cada partida y avisa con un resumen al terminar",
    "Remove the shaders from this game": "Quitar los shaders de este juego",
    "Repos/Flatpak/GitHub install here. AUR packages are reviewed first, then built in a terminal. GitHub installs update from UPDATES.": "Los repos, Flatpak y GitHub se instalan aquí. Los paquetes de AUR se revisan antes y luego se compilan en una terminal. Lo instalado desde GitHub se actualiza desde ACTUALIZACIONES.",
    "Restart the PC": "Reinicia el PC",
    "Route: ": "Vía: ",
    "Run INSTALL above first": "Pulsa antes INSTALAR arriba",
    "Runtimes and extensions no app needs.": "Runtimes y extensiones que no necesita ninguna app.",
    "SAVE FAILED": "NO SE PUDO GUARDAR",
    "SAVE": "GUARDAR",
    "SAVED ✓": "GUARDADO ✓",
    "SAVED": "GUARDADOS",
    "SAVING LINK…": "GUARDANDO ENLACE…",
    "SAVING…": "GUARDANDO…",
    "SCAN": "ESCANEAR",
    "SCANNING THE SYSTEM…": "ESCANEANDO EL SISTEMA…",
    "SCANNING YOUR LIBRARY…": "ESCANEANDO TU BIBLIOTECA…",
    "SCANNING…": "ESCANEANDO…",
    "SCHEDULER": "PLANIFICADOR",
    "SCHEDULER…": "PLANIFICADOR…",
    "SCREENSHOT KEY": "TECLA CAPTURA",
    "SEARCH FOR AN APP": "BUSCA UNA APP",
    "SEARCH NEXUS ↗": "BUSCAR EN NEXUS ↗",
    "SEARCH": "BUSCAR",
    "SEARCHING…": "BUSCANDO…",
    "SELECT AN APP": "ELIGE UNA APP",
    "SET UP ALL (": "CONFIGURAR TODO (",
    "SET UP": "CONFIGURAR",
    "SETTING KEY…": "CAMBIANDO TECLA…",
    "SETTING PROTON…": "CAMBIANDO PROTON…",
    "SETTING UP ": "CONFIGURANDO ",
    "SETTING UP RESHADE…": "CONFIGURANDO RESHADE…",
    "SETTINGS ▴": "AJUSTES ▴",
    "SETTINGS ▾": "AJUSTES ▾",
    "SHADER CACHES": "CACHÉS DE SHADERS",
    "SHARED": "COMPARTIDO",
    "SHARPEN + AA": "NITIDEZ + AA",
    "SHARPEN": "NITIDEZ",
    "SIZE": "TAMAÑO",
    "SMAA anti-aliasing, then CAS sharpening": "Antialiasing SMAA y después nitidez CAS",
    "SNAPSHOTTING…": "HACIENDO SNAPSHOT…",
    "STALE": "OBSOLETA",
    "STASH": "ALMACÉN",
    "STATUS": "ESTADO",
    "STEAM DEFAULT": "POR DEFECTO DE STEAM",
    "STEPS": "PASOS",
    "STOP": "PARAR",
    "STORE": "TIENDA",
    "SUMMARY OFF": "RESUMEN OFF",
    "SUPPORTED FORMATS": "FORMATOS ADMITIDOS",
    "SWITCHING API…": "CAMBIANDO API…",
    "SWITCHING…": "CAMBIANDO…",
    "SYSTEM": "SISTEMA",
    "Saved in Umbral itself (it applies them at once if it's open). A · means it comes from the prefix; Battle.net's options are its prefix's.": "Se guardan en el propio Umbral (si está abierto, las aplica al momento). Un · indica que viene del prefix; las opciones de Battle.net son las de su prefix.",
    "Saves your packages (repos and AUR), Flatpaks, GitHub AppImages and the launchers you edited (with their icons) to ~/control-deck-backup-<date>.json.": "Guarda tus paquetes (repos y AUR), Flatpaks, AppImages de GitHub y los lanzadores que editaste (con sus iconos) en ~/control-deck-backup-<fecha>.json.",
    "ScummVM game": "Juego de ScummVM",
    "Set on this game. Click to switch it.": "Fijado en este juego. Pulsa para cambiarlo.",
    "Shader caches": "Cachés de shaders",
    "Ships: ": "Trae: ",
    "Shows the upscaler's own watermark in game, to confirm the upgrade is active": "Muestra la marca de agua del escalador en el juego, para confirmar que la mejora está activa",
    "Some games quick-load with F9": "Algunos juegos cargan partida rápida con F9",
    "Sources and builds kept by yay/paru.": "Fuentes y compilaciones que guardan yay/paru.",
    "Spikes": "Picos",
    "Steam (shared, non-Steam shortcuts)": "Steam (compartido, accesos no de Steam)",
    "Steam default": "Por defecto de Steam",
    "Steam is compiling shaders right now; cleaning waits until it finishes. ": "Steam está compilando shaders ahora mismo; la limpieza espera a que termine. ",
    "Steam must be closed to change it": "Steam tiene que estar cerrado para cambiarlo",
    "Steam takes screenshots with F12 by default": "Steam hace capturas con F12 por defecto",
    "Switch to ": "Cambiar a ",
    "TEMPERATURE": "TEMPERATURA",
    "THIRD-PARTY REPO": "REPO DE TERCEROS",
    "THIS GAME": "ESTE JUEGO",
    "TOOL": "HERRAMIENTA",
    "TURNING OFF…": "DESACTIVANDO…",
    "TYPE AN APP AND PRESS ENTER": "ESCRIBE UNA APP Y PULSA ENTER",
    "Temperatures, load and power are sampled every 5 s while a game runs (Steam through the deck, Umbral 0.10+).": "Temperaturas, carga y consumo se miden cada 5 s mientras juegas (Steam a través de la app, Umbral 0.10+).",
    "The game doesn't ship DLSS.": "El juego no trae DLSS.",
    "The game doesn't ship FSR 3.1 as a DLL (FSR 2/3.0 inside the .exe can't be swapped).": "El juego no trae FSR 3.1 como DLL (FSR 2/3.0 dentro del .exe no se puede sustituir).",
    "The game doesn't ship XeSS.": "El juego no trae XeSS.",
    "The game must launch through Control Deck: LIBRARY → USE IN STEAM first.": "El juego tiene que lanzarse a través de Control Deck: antes, BIBLIOTECA → USAR EN STEAM.",
    "The game reads and writes the disk ahead of other programs (ionice best-effort, level 0). It helps when something else uses the disk while you play: downloads, updates, copies.": "El juego lee y escribe en el disco por delante de otros programas (ionice best-effort, nivel 0). Ayuda si otra cosa usa el disco mientras juegas: descargas, actualizaciones, copias.",
    "The game renders with Vulkan: ReShade's DLL can't hook it here, vkBasalt can.": "El juego renderiza con Vulkan: la DLL de ReShade no puede engancharse aquí; vkBasalt sí.",
    "The game ships FSR 3.1 for Vulkan; the FSR 4 upgrade is DirectX 12 only.": "El juego trae FSR 3.1 para Vulkan; la mejora a FSR 4 es solo para DirectX 12.",
    "The game's FSR 3.1 runs as FSR 4 (AMD's ML upscaler). Proton downloads the DLL. SAVE to apply.": "El FSR 3.1 del juego pasa a funcionar como FSR 4 (el escalador con IA de AMD). Proton descarga la DLL. GUARDAR para aplicar.",
    "The key most preset guides suggest": "La tecla que sugieren casi todas las guías de presets",
    "The most trustworthy result named like your search": "El resultado más fiable que se llama como lo que buscas",
    "The profile applies on every launch from Steam.": "El perfil se aplica cada vez que se lanza desde Steam.",
    "The recommended one for this game. ": "La recomendada para este juego. ",
    "This game has no presets yet.": "Este juego aún no tiene presets.",
    "This game is drawn in 2D with GDI (RPG Maker style), not with DirectX, OpenGL or Vulkan: neither ReShade nor vkBasalt can hook it. TEMPS still works (LIBRARY).": "Este juego se dibuja en 2D con GDI (estilo RPG Maker), no con DirectX, OpenGL ni Vulkan: ni ReShade ni vkBasalt pueden engancharse. TEMPS sí funciona (BIBLIOTECA).",
    "This game's Proton can't do it: pick GE-Proton or Proton-CachyOS in PROTON.": "El Proton de este juego no lo admite: elige GE-Proton o Proton-CachyOS en PROTON.",
    "This game's disk honours it: ": "El disco de este juego la respeta: ",
    "To go back: boot the snapshot from your boot menu (or a live USB), then run  sudo snapper rollback  and reboot.": "Para volver atrás: arranca el snapshot desde el menú de arranque (o un USB live), ejecuta  sudo snapper rollback  y reinicia.",
    "To go back: reboot, open \"Arch Linux snapshots\" in GRUB (grub-btrfs), boot the snapshot and check everything works, then run  sudo snapper rollback  and reboot.": "Para volver atrás: reinicia, abre \"Arch Linux snapshots\" en GRUB (grub-btrfs), arranca el snapshot, comprueba que todo funciona, ejecuta  sudo snapper rollback  y reinicia.",
    "Turn on Performance Mode once you like it. Screenshots (PRINT SCREEN): ": "Activa Performance Mode cuando te guste. Capturas (IMPR PANT): ",
    "Turn on to get a notification when updates are available (the deck doesn't need to be open).": "Actívalo para recibir un aviso cuando haya actualizaciones (no hace falta tener la app abierta).",
    "UNINSTALL": "DESINSTALAR",
    "UP TO DATE ✓": "AL DÍA ✓",
    "UPDATE ALL": "ACTUALIZAR TODO",
    "UPDATE DATA": "ACTUALIZAR DATOS",
    "UPDATE": "ACTUALIZAR",
    "UPDATES": "ACTUALIZACIONES",
    "UPDATING ": "ACTUALIZANDO ",
    "UPDATING ALL…": "ACTUALIZANDO TODO…",
    "UPSCALE": "ESCALADO",
    "USE IN STEAM moves these options into the profile (Steam must be closed).": "USAR EN STEAM pasa estas opciones al perfil (Steam tiene que estar cerrado).",
    "USE IN STEAM puts the deck in its launch options.": "USAR EN STEAM pone la app en sus opciones de lanzamiento.",
    "USE IN STEAM": "USAR EN STEAM",
    "USE RESHADE ★": "USAR RESHADE ★",
    "USE VKBASALT ★": "USAR VKBASALT ★",
    "Umbral asks the deck for the shaders/TEMPS each time it starts the game.": "Umbral pide a la app los shaders y TEMPS cada vez que arranca el juego.",
    "Under 10 votes: few people have checked it": "Menos de 10 votos: poca gente lo ha revisado",
    "Unused Flatpak runtimes": "Runtimes de Flatpak sin usar",
    "Unused Proton versions": "Versiones de Proton sin usar",
    "Uploaded under 30 days ago with few votes: the usual shape of malicious AUR packages. Read its review carefully.": "Subido hace menos de 30 días y con pocos votos: el perfil típico de los paquetes maliciosos del AUR. Lee bien su revisión.",
    "VAR=value VAR2=value (this game)": "VAR=valor VAR2=valor (este juego)",
    "VERIFIED": "VERIFICADO",
    "VISUAL SHADERS": "SHADERS VISUALES",
    "Variable refresh rate (FreeSync / G-Sync) is on.": "La frecuencia de refresco variable (FreeSync / G-Sync) está activada.",
    "Variable refresh rate is off. In Hyprland, misc:vrr turns it on (2 = fullscreen apps only, good for games).": "La frecuencia de refresco variable está desactivada. En Hyprland, misc:vrr la activa (2 = solo apps a pantalla completa, bien para juegos).",
    "Visual shaders (ReShade / vkBasalt) for this game": "Shaders visuales (ReShade / vkBasalt) para este juego",
    "Visual shaders (vkBasalt): sharpening, anti-aliasing, ReShade presets": "Shaders visuales: nitidez, antialiasing y presets de ReShade",
    "Vulkan devices": "dispositivos Vulkan",
    "Vulkan loader": "cargador de Vulkan",
    "WHILE PLAYING": "MIENTRAS JUEGAS",
    "WORKING": "TRABAJANDO",
    "WRAPPING…": "ENVOLVIENDO…",
    "Web search for ReShade presets of this game on Nexus Mods": "Búsqueda web de presets de ReShade de este juego en Nexus Mods",
    "Web search for this game's ReShade presets on Nexus Mods": "Búsqueda web de presets de ReShade de este juego en Nexus Mods",
    "Will delete snapshot(s): #": "Se borrarán los snapshots: #",
    "Wine prefixes of uninstalled Steam games (each one is backed up first).": "Prefixes de Wine de juegos de Steam desinstalados (se hace copia de cada uno antes).",
    "Writes default_sched in /etc/scx_loader.toml (password): lavd Gaming from every boot": "Escribe default_sched en /etc/scx_loader.toml (contraseña): lavd Gaming desde cada arranque",
    "XeSS (newest)": "XeSS (más reciente)",
    "Your saved preset: ": "Tu preset guardado: ",
    "Your snapper config only lets root list snapshots. Load them once with your password, or allow your user to list them (adds you to ALLOW_USERS — reading only; creating still asks for the password).": "Tu configuración de snapper solo deja ver los snapshots a root. Cárgalos una vez con tu contraseña o permite a tu usuario verlos (te añade a ALLOW_USERS, solo lectura; crear sigue pidiendo la contraseña).",
    "\nClick again to confirm.\n": "\nPulsa otra vez para confirmar.\n",
    "\uf108  This update changes the GPU driver (": "\uf108  Esta actualización cambia el driver de la GPU (",
    "after the game, e.g. -novid": "tras el juego, p. ej. -novid",
    "all good": "todo bien",
    "amdgpu kernel driver": "driver del kernel amdgpu",
    "app name": "nombre de la app",
    "args (replace the profile's)": "argumentos (sustituyen los del perfil)",
    "at boot: ": "al arrancar: ",
    "at its power limit: normal under load, odd at idle": "en su límite de consumo: normal con carga, raro en reposo",
    "auto-check off": "comprobación auto off",
    "auto-check on": "comprobación auto on",
    "autostart ": "autoarranque ",
    "available": "disponible",
    "before the game, e.g. gamescope -f --": "antes del juego, p. ej. gamescope -f --",
    "below 1048576: some games crash (see HEALTH)": "por debajo de 1048576: algunos juegos se cierran (mira SALUD)",
    "benchmark ": "prueba ",
    "chaotic-aur: AUR packages built by a third party; trust is the AUR package's": "chaotic-aur: paquetes del AUR compilados por un tercero; la confianza es la del paquete del AUR",
    "clean": "limpiar",
    "closed": "cerrado",
    "description for a new snapshot…": "descripción del nuevo snapshot…",
    "download it, then IMPORT": "descárgalo y pulsa IMPORTAR",
    "edit": "editar",
    "export": "exportar",
    "extra env: VAR=1 VAR2=x": "variables extra: VAR=1 VAR2=x",
    "filter…": "filtrar…",
    "fix": "arreglar",
    "from the first game that starts until the last one closes": "desde que empieza el primer juego hasta que se cierra el último",
    "game crashed": "juego cerrado con error",
    "game name on SweetFX Settings DB": "nombre del juego en SweetFX Settings DB",
    "game profile": "perfil de juego",
    "gamemode group": "grupo gamemode",
    "gaming import": "importar gaming",
    "group added: log out and back in": "grupo añadido: cierra sesión y vuelve a entrar",
    "hover a tag to see what it means": "pasa el ratón por una etiqueta para ver qué significa",
    "icon name or /path": "nombre del icono o /ruta",
    "in the gamemode group": "en el grupo gamemode",
    "in use": "en uso",
    "install": "instalar",
    "installed Steam games and Umbral games show up here": "aquí aparecen los juegos instalados de Steam y Umbral",
    "is OFF (snapper-cleanup.timer disabled)": "está DESACTIVADA (snapper-cleanup.timer desactivado)",
    "kernel default (EEVDF)": "el del kernel (EEVDF)",
    "kernel sync for Wine/Proton": "sincronización del kernel para Wine/Proton",
    "last 5 minutes while STATUS is open": "últimos 5 minutos con ESTADO abierto",
    "launch": "lanzar",
    "lavd Gaming starts with each game and stops when it closes (only if no scheduler was running)": "lavd Gaming arranca con cada juego y se para al cerrarlo (solo si no había otro planificador)",
    "load ": "carga ",
    "manual snapshot": "snapshot manual",
    "multilib repository": "repositorio multilib",
    "name": "nombre",
    "never played": "sin jugar",
    "no game  ·  Steam ": "ningún juego  ·  Steam ",
    "no lib32-pipewire / lib32-libpulse: 32-bit games have no sound": "sin lib32-pipewire / lib32-libpulse: los juegos de 32 bits no tienen sonido",
    "no orphans": "sin huérfanos",
    "no shaders possible": "sin shaders posibles",
    "no swappable upscaler DLL": "ninguna DLL de escalado sustituible",
    "none installed": "ninguno instalado",
    "not available": "no disponible",
    "not in the gamemode group: it can't switch the governor": "no estás en el grupo gamemode: no puede cambiar el governor",
    "not in this kernel (needs 6.14 or newer); Proton falls back to esync/fsync": "no está en este kernel (necesita 6.14 o superior); Proton usa esync/fsync en su lugar",
    "not installed (optional)": "no instalado (opcional)",
    "not installed": "no instalado",
    "nothing heavy to render right now": "ahora no tiene nada pesado que renderizar",
    "nothing to clean": "nada que limpiar",
    "off: Wayland sessions and gamescope need it; reboot after the fix": "desactivado: lo necesitan Wayland y gamescope; reinicia tras arreglarlo",
    "official repos · AUR · Flatpak · GitHub releases": "repos oficiales · AUR · Flatpak · releases de GitHub",
    "on (needed by Wayland and gamescope)": "activado (lo necesitan Wayland y gamescope)",
    "open": "abierto",
    "opens ReShade's menu in game": "abre el menú de ReShade en el juego",
    "other ": "otros ",
    "p99 frame ms": "ms del fotograma p99",
    "paste a preset page (Nexus…) to keep it here": "pega una página de preset (Nexus…) para guardarla aquí",
    "path, download URL or github.com/user/repo…": "ruta, URL de descarga o github.com/usuario/repo…",
    "permission ": "permiso ",
    "permission reset": "permisos restablecidos",
    "pipelines = Steam's Fossilize recordings (driver-independent, used to pre-compile) · driver = the GPU driver's compiled cache (NVIDIA nvidiav1 / Mesa for AMD-Intel), rebuilt after every driver update. DRIVER CACHE clears only that; ALL clears the game's whole folder. Either way the next launches stutter a little while caches rebuild.": "pipelines = grabaciones de Fossilize de Steam (independientes del driver, sirven para precompilar) · driver = la caché compilada del driver de la GPU (NVIDIA nvidiav1 / Mesa en AMD e Intel), que se rehace con cada actualización del driver. CACHÉ DEL DRIVER borra solo eso; TODO borra la carpeta entera del juego. En ambos casos los siguientes arranques darán algún tirón mientras se rehacen las cachés.",
    "play a game: a summary appears here when it closes": "juega a algo: al cerrarlo aparecerá aquí un resumen",
    "play": "jugar",
    "players with a GPU like yours": "jugadores con una GPU como la tuya",
    "players with your GPU vendor": "jugadores con tu marca de GPU",
    "prefix backup": "copia de prefix",
    "prefix clone": "clonar prefix",
    "prefix delete": "borrar prefix",
    "prefix restore": "restaurar prefix",
    "preset file: ": "archivo del preset: ",
    "preset pages you keep for this game (e.g. from Nexus)": "páginas de presets que guardas para este juego (p. ej. de Nexus)",
    "proton install": "instalar proton",
    "protondb data": "datos de protondb",
    "repos · AUR · Flatpak · AppImage/GitHub": "repos · AUR · Flatpak · AppImage/GitHub",
    "reshade install": "instalar reshade",
    "reshade on": "reshade activado",
    "restore": "restaurar",
    "running": "en marcha",
    "runs hourly": "se ejecuta cada hora",
    "save a preset page": "guarda una página de preset",
    "saves a screenshot with the effects to ": "guarda una captura con los efectos en ",
    "scx-tools not installed": "scx-tools no instalado",
    "scx_lavd in Gaming mode until you stop it or reboot (asks for your password)": "scx_lavd en modo Gaming hasta que lo pares o reinicies (pide tu contraseña)",
    "search repos · AUR · flatpak…  or  github.com/user/repo": "busca en repos · AUR · flatpak…  o  github.com/usuario/repo",
    "shader cache clean": "limpiar caché de shaders",
    "shader install": "instalar shaders",
    "shader packs: ": "packs de shaders: ",
    "snap-pac is installed: every pacman operation already gets a pre/post snapshot.": "snap-pac está instalado: cada operación de pacman ya tiene su snapshot pre/post.",
    "snap-pac is not installed: the deck takes a snapshot itself before pacman changes.": "snap-pac no está instalado: la app hace ella misma un snapshot antes de cambios con pacman.",
    "snapper has no '": "snapper no tiene la configuración '",
    "snapshot cleanup": "limpieza de snapshots",
    "snapshot delete": "borrar snapshot",
    "snapshot": "snapshot",
    "snapshots allow": "permitir snapshots",
    "state ": "estado ",
    "steam launch ": "lanzamiento steam ",
    "switches all effects on/off in game — compare, or drop them in heavy scenes": "activa o desactiva todos los efectos en el juego: para comparar o quitarlos en escenas pesadas",
    "the kernel has the module but it is not loaded": "el kernel trae el módulo pero no está cargado",
    "turns the effects on/off in game": "activa o desactiva los efectos en el juego",
    "uninstall": "desinstalar",
    "uninstalled app ": "app desinstalada ",
    "update": "actualizar",
    "updated ": "actualizado ",
    "visual shaders": "shaders visuales",
    "vkBasalt also works (via DXVK/VKD3D) if you prefer nothing in the game folder; presets get converted and lose depth effects.": "vkBasalt también funciona (vía DXVK/VKD3D) si prefieres no tocar la carpeta del juego; los presets se convierten y pierden los efectos de profundidad.",
    "vkBasalt comes from chaotic-aur, which isn't enabled here. Enable it (or build vkbasalt + lib32-vkbasalt from the AUR), then come back.": "vkBasalt viene de chaotic-aur, que no está activado aquí. Actívalo (o compila vkbasalt + lib32-vkbasalt desde AUR) y vuelve.",
    "vkBasalt isn't installed here → FX → INSTALL": "vkBasalt no está instalado aquí → FX → INSTALAR",
    "vkBasalt not installed": "vkBasalt no instalado",
    "while playing: ": "mientras juegas: ",
    "Δ B vs A": "Δ B frente a A",
    "≥ 1048576: enough for any game": "≥ 1048576: suficiente para cualquier juego",
    "■ STOP": "■ DETENER",
    "▶ PLAY": "▶ JUGAR",
    "◆ DECK": "◆ APP",
    "○ No shaders on this game": "○ Sin shaders en este juego",
    "○ Steam options: ": "○ Opciones de Steam: ",
    "● ACTIVE: ": "● ACTIVO: ",
    "● Launched through Control Deck": "● Se lanza a través de Control Deck",
    "● NEW VERSION": "● NUEVA VERSIÓN",
    "● READY": "● LISTO",
    "★ RECOMMENDED": "★ RECOMENDADO",
    "★ SUGGESTED FOR THIS PC": "★ SUGERIDO PARA ESTE PC",
    "⚠ Has online multiplayer/co-op: fine for single-player, check the game's rules online": "⚠ Tiene multijugador o cooperativo online: bien para un jugador, revisa las normas del juego online",
    "⚠ ONLINE GAME WITH ANTI-CHEAT (": "⚠ JUEGO ONLINE CON ANTI-CHEAT (",
    "⚠ Online multiplayer game: some online games forbid visual mods in their rules. Check before using shaders there.": "⚠ Juego multijugador online: algunos juegos online prohíben los mods visuales en sus normas. Compruébalo antes de usar shaders.",
    "⚠ This game doesn't launch through Control Deck yet, so the shaders won't load. ": "⚠ Este juego aún no se lanza a través de Control Deck, así que los shaders no se cargarán. ",
    "⚠ Umbral 0.10.0 or newer is needed: it asks the deck for shaders and TEMPS before starting the game. Update Umbral.": "⚠ Hace falta Umbral 0.10.0 o posterior: pide a la app los shaders y TEMPS antes de arrancar el juego. Actualiza Umbral.",
    "✓ AUTO-CHECK ON": "✓ COMPROBACIÓN AUTO ON",
    "✓ AUTOSTART": "✓ INICIO AUTOMÁTICO",
    "✓ DELETE DATA": "✓ BORRAR DATOS",
    "✓ Everything games need is in place (": "✓ Todo lo que necesitan los juegos está en orden (",
    "✓ No suspicious patterns found. Still, only build packages you trust.": "✓ No se encontró nada sospechoso. Aun así, compila solo paquetes de confianza.",
    "✓ SUMMARY": "✓ RESUMEN",
    "✗ Anti-cheat (": "✗ Anti-cheat (",
    "✗ ReShade is banned or blocked in this game (PCGamingWiki): not touched": "✗ ReShade está vetado o bloqueado en este juego (PCGamingWiki): no se toca",
};
// sentences with values inside: [regex, replacement]
var PATTERNS = [
    [new RegExp("^Online game with anti-cheat \\((.*)\\): neither is safe there\\.$"), "Juego online con anti-cheat ($1): ninguno es seguro ahí."],
    [new RegExp("^(DirectX 10–12|DirectX 9|OpenGL|A Windows game) under Proton: ReShade itself runs presets exactly as made, depth effects included, with its in-game menu to tweak them\\.$"), "$1 con Proton: ReShade de verdad aplica los presets tal cual, con efectos de profundidad, y tiene su menú en el juego para ajustarlos."],
    [new RegExp("^Your current preset has (\\d+) depth effect\\(s\\) vkBasalt has to skip\\.$"), "Tu preset actual tiene $1 efecto(s) de profundidad que vkBasalt tendría que omitir."],
    [new RegExp("^missing: (.*)$"), "falta: $1"],
    [new RegExp("^loaded(.*)$"), "cargado$1"],
    [new RegExp("^enabled in (.*) \\(32-bit libraries for Steam and Wine\\)$"), "activado en $1 (librerías de 32 bits para Steam y Wine)"],
    [new RegExp("^(.*) present: Proton/Wine can use kernel sync$"), "$1 presente: Proton/Wine pueden usar la sincronización del kernel"],
    [new RegExp("^no NVIDIA, AMD or Intel GPU found in (.*)$"), "no se encontró ninguna GPU NVIDIA, AMD ni Intel en $1"],
    [new RegExp("^install vulkan-tools to check which GPUs Vulkan sees \\(drivers: (.*)\\)$"), "instala vulkan-tools para ver qué GPUs ve Vulkan (drivers: $1)"],
];
