.pragma library
// Spanish UI text for System Deck: keys are the English strings of shell.qml (and the
// fixed sentences the backend shows), exactly. Missing keys fall back to English.
var ES = {
    "  ·  data ": "  ·  datos ",
    "  ·  since ": "  ·  desde ",
    "  ·  updated ": "  ·  actualizado ",
    " APPS": " APPS",
    " Arch news since your last upgrade — some need manual steps. Read them before updating:": " noticias de Arch desde tu última actualización; algunas requieren pasos manuales. Léelas antes de actualizar:",
    " FILE": " ARCHIVO",
    " FILES": " ARCHIVOS",
    " GAMES": " JUEGOS",
    " PENDING": " PENDIENTES",
    " READY": " LISTOS",
    " RESULTS": " RESULTADOS",
    " SNAPSHOTS": " SNAPSHOTS",
    " Space limits need Btrfs quotas (off).": " Los límites de espacio necesitan cuotas de Btrfs (desactivadas).",
    " TO CLEAN": " PARA LIMPIAR",
    " downloads": " descargas",
    " downloads)": " descargas)",
    " effect": " efecto",
    " file(s) can't be installed and will be skipped (rpm / deb without debtap / unknown).": " archivo(s) no se pueden instalar y se omitirán (rpm / deb sin debtap / desconocido).",
    " important), none younger than ": " importantes), ninguno más reciente que ",
    " is ": " es ",
    " numbered snapshots (": " snapshots numerados (",
    " problem": " problema",
    " risk": " riesgo",
    " skipped": " omitidos",
    " updates": " actualizaciones",
    " uses ": ") usa ",
    " votes": " votos",
    " warning": " aviso",
    " → NOW": " → AHORA",
    "' config on this system: nothing to show.": "' en este sistema: no hay nada que mostrar.",
    "+ DELETE DATA": "+ BORRAR DATOS",
    ".deb  (with debtap)": ".deb  (con debtap)",
    "// log output": "// registro",
    "/mo": "/mes",
    "100+ votes on the AUR": "Más de 100 votos en el AUR",
    ": keeps ": ": guarda ",
    "A repository that isn't Arch's or CachyOS's": "Un repositorio que no es de Arch ni de CachyOS",
    "ALL CLEAN ✓": "TODO LIMPIO ✓",
    "ALL UP TO DATE ✓": "TODO AL DÍA ✓",
    "ALL": "TODO",
    "ALLOW MY USER": "PERMITIR A MI USUARIO",
    "ALLOWING…": "PERMITIENDO…",
    "ANALYZING…": "ANALIZANDO…",
    "APPS DIR": "CARPETA APPS",
    "AUR cache": "Caché de AUR",
    "AUR votes: users who vouch for the package": "Votos en el AUR: usuarios que respaldan el paquete",
    "AUTO-CHECK OFF": "COMPROBACIÓN AUTO OFF",
    "AUTOSTART": "INICIO AUTOMÁTICO",
    "AWAITING FILE": "ESPERANDO ARCHIVO",
    "Arch doesn't support partial upgrades: repo packages are updated together (pacman -Syu). AUR opens a terminal.": "Arch no admite actualizaciones parciales: los paquetes de los repos se actualizan juntos (pacman -Syu). AUR abre una terminal.",
    "Auto-cleanup ": "Limpieza automática ",
    "BACKUP": "COPIA",
    "BUILD & INSTALL": "COMPILAR E INSTALAR",
    "BUILD ANYWAY": "COMPILAR IGUALMENTE",
    "Broken launchers": "Lanzadores rotos",
    "Building runs the PKGBUILD on your machine. Read it if anything is flagged.": "Compilar ejecuta el PKGBUILD en tu equipo. Léelo si se ha marcado algo.",
    "CANCEL": "CANCELAR",
    "CHECK": "COMPROBAR",
    "CHECKING FOR UPDATES…": "BUSCANDO ACTUALIZACIONES…",
    "CHECKING": "COMPROBANDO",
    "CHECKING…": "COMPROBANDO…",
    "CLEAN": "LIMPIAR",
    "CLEANING UP…": "LIMPIANDO…",
    "CLEANING…": "LIMPIANDO…",
    "CLEANUP NOW": "LIMPIAR AHORA",
    "CLEAR": "BORRAR",
    "CLICK AGAIN TO CONFIRM": "PULSA OTRA VEZ PARA CONFIRMAR",
    "COMPARING…": "COMPARANDO…",
    "CONFIRM ": "CONFIRMAR ",
    "CONFIRM?": "¿CONFIRMAR?",
    "COPIED ✓": "COPIADO ✓",
    "COPY": "COPIAR",
    "CREATE": "CREAR",
    "Checked every 6 h in the background: you get a notification, even with the deck closed.": "Se comprueba cada 6 h en segundo plano: recibes una notificación aunque la app esté cerrada.",
    "Choose a System Deck backup (.json)": "Elige una copia de System Deck (.json)",
    "Choose an icon": "Elige un icono",
    "System Deck downloads": "Descargas de System Deck",
    "DELETE (": "BORRAR (",
    "DELETE": "BORRAR",
    "DELETING…": "BORRANDO…",
    "DIFF → NOW": "DIFF → AHORA",
    "DONE WITH ERRORS": "TERMINADO CON ERRORES",
    "DONE ✓": "HECHO ✓",
    "DOWNLOAD FAILED": "FALLÓ LA DESCARGA",
    "DOWNLOADING…": "DESCARGANDO…",
    "DROP PACKAGE(S) HERE": "SUELTA AQUÍ LOS PAQUETES",
    "Dependencies no package needs any more (pacman -Rns).": "Dependencias que ya no necesita ningún paquete (pacman -Rns).",
    "EDIT": "EDITAR",
    "EXECUTABLE": "EJECUTABLE",
    "EXPORT BACKUP": "EXPORTAR COPIA",
    "EXPORT": "EXPORTAR",
    "EXPORTING…": "EXPORTANDO…",
    "FAILED · ": "FALLÓ · ",
    "FEW VOTES": "POCOS VOTOS",
    "FILE": "ARCHIVO",
    "FIX FAILED": "NO SE PUDO ARREGLAR",
    "FIXED ✓": "ARREGLADO ✓",
    "FIXING…": "ARREGLANDO…",
    "FOLDER": "CARPETA",
    "Files downloaded from GitHub/URLs.": "Archivos descargados de GitHub o URLs.",
    "Flagged out of date on the AUR": "Marcado como desactualizado en el AUR",
    "Flathub installs last month": "Instalaciones en Flathub el último mes",
    "Flathub verified the developer: it comes from the app's own authors": "Flathub verificó al desarrollador: viene de los propios autores de la app",
    "GAME": "JUEGO",
    "HIDDEN": "OCULTO",
    "HISTORY": "HISTORIAL",
    "INSTALL ": "INSTALAR ",
    "INSTALL ALL": "INSTALAR TODO",
    "INSTALL": "INSTALAR",
    "INSTALLED": "INSTALADO",
    "INSTALLING ": "INSTALANDO ",
    "INSTALLING…": "INSTALANDO…",
    "Install ": "Instalar ",
    "Installs whatever is missing from a backup: repo packages with pacman, Flatpaks, GitHub AppImages and launchers. AUR packages are built in a terminal.": "Instala lo que falte de una copia: paquetes de los repos con pacman, Flatpaks, AppImages de GitHub y lanzadores. Los paquetes de AUR se compilan en una terminal.",
    "LAUNCH FAILED ✗": "NO SE PUDO LANZAR ✗",
    "LAUNCH": "LANZAR",
    "LAUNCHING…": "LANZANDO…",
    "LESS ▴": "MENOS ▴",
    "LOAD (PASSWORD)": "CARGAR (CONTRASEÑA)",
    "LOAD": "CARGA",
    "LOADING SNAPSHOTS…": "CARGANDO SNAPSHOTS…",
    "MANAGE": "GESTIONAR",
    "MORE ▾": "MÁS ▾",
    "Menu entries whose program no longer exists (moved to a trash folder).": "Entradas del menú cuyo programa ya no existe (se mueven a una papelera).",
    "NEW · FEW VOTES": "NUEVO · POCOS VOTOS",
    "NEW": "NUEVO",
    "NO FILE": "SIN ARCHIVO",
    "NO OPERATIONS YET": "AÚN NO HAY OPERACIONES",
    "NO RESULTS FOR «": "SIN RESULTADOS PARA «",
    "NO SNAPSHOTS LOADED": "NO HAY SNAPSHOTS CARGADOS",
    "NONE INSTALLABLE": "NADA INSTALABLE",
    "NONE": "NINGUNO",
    "NOT CHECKED": "SIN COMPROBAR",
    "No maintainer: nobody updates or checks it": "Sin mantenedor: nadie lo actualiza ni lo revisa",
    "Nothing to clean in: ": "Nada que limpiar en: ",
    "OFFICIAL": "OFICIAL",
    "ORPHAN": "HUÉRFANO",
    "ORPHANED (no maintainer)": "HUÉRFANO (sin mantenedor)",
    "OUT OF DATE": "DESACTUALIZADO",
    "Official Arch / CachyOS repository: built and signed by the distribution": "Repositorio oficial de Arch / CachyOS: compilado y firmado por la distribución",
    "Old package versions (the latest one is kept: paccache -rk1).": "Versiones antiguas de paquetes (se guarda la última: paccache -rk1).",
    "Orphan packages": "Paquetes huérfanos",
    "PERMS": "PERMISOS",
    "POPULAR": "POPULAR",
    "PREBUILT AUR": "AUR PRECOMPILADO",
    "PRESS CHECK": "PULSA COMPROBAR",
    "PRESS RESCAN": "PULSA VOLVER A ESCANEAR",
    "PROFILE": "PERFIL",
    "Pacman cache": "Caché de pacman",
    "READ THE ARCH NEWS FIRST · CLICK AGAIN": "LEE ANTES LAS NOTICIAS DE ARCH · PULSA OTRA VEZ",
    "READING THE PKGBUILD…": "LEYENDO EL PKGBUILD…",
    "REALLY BUILD?": "¿COMPILAR DE VERDAD?",
    "REFRESH": "ACTUALIZAR",
    "REMOVED ✓": "QUITADO ✓",
    "RESCAN": "VOLVER A ESCANEAR",
    "RESET": "RESTABLECER",
    "RESTORE": "RESTAURAR",
    "RESTORING…": "RESTAURANDO…",
    "REVIEW AND CONFIRM": "REVISAR Y CONFIRMAR",
    "REVIEW FAILED": "FALLÓ LA REVISIÓN",
    "REVIEW": "REVISAR",
    "REVIEWING ": "REVISANDO ",
    "RISK: ": "RIESGO: ",
    "RUN ": "PRUEBA ",
    "RUNNING ▶": "EN MARCHA ▶",
    "RUNNING": "EN EJECUCIÓN",
    "Reading ": "Leyendo ",
    "Repos/Flatpak/GitHub install here. AUR packages are reviewed first, then built in a terminal. GitHub installs update from UPDATES.": "Los repos, Flatpak y GitHub se instalan aquí. Los paquetes de AUR se revisan antes y luego se compilan en una terminal. Lo instalado desde GitHub se actualiza desde ACTUALIZACIONES.",
    "Restart the PC": "Reinicia el PC",
    "Runtimes and extensions no app needs.": "Runtimes y extensiones que no necesita ninguna app.",
    "SAVE FAILED": "NO SE PUDO GUARDAR",
    "SAVE": "GUARDAR",
    "SAVED ✓": "GUARDADO ✓",
    "SAVED": "GUARDADOS",
    "SCAN": "ESCANEAR",
    "SCANNING THE SYSTEM…": "ESCANEANDO EL SISTEMA…",
    "SCANNING…": "ESCANEANDO…",
    "SEARCH FOR AN APP": "BUSCA UNA APP",
    "SEARCH": "BUSCAR",
    "SEARCHING…": "BUSCANDO…",
    "SELECT AN APP": "ELIGE UNA APP",
    "SIZE": "TAMAÑO",
    "SNAPSHOTTING…": "HACIENDO SNAPSHOT…",
    "STASH": "ALMACÉN",
    "STATUS": "ESTADO",
    "STORE": "TIENDA",
    "SUPPORTED FORMATS": "FORMATOS ADMITIDOS",
    "SYSTEM": "SISTEMA",
    "Saves your packages (repos and AUR), Flatpaks, GitHub AppImages and the launchers you edited (with their icons) to ~/system-deck-backup-<date>.json.": "Guarda tus paquetes (repos y AUR), Flatpaks, AppImages de GitHub y los lanzadores que editaste (con sus iconos) en ~/system-deck-backup-<fecha>.json.",
    "Sources and builds kept by yay/paru.": "Fuentes y compilaciones que guardan yay/paru.",
    "THIRD-PARTY REPO": "REPO DE TERCEROS",
    "TYPE AN APP AND PRESS ENTER": "ESCRIBE UNA APP Y PULSA ENTER",
    "The most trustworthy result named like your search": "El resultado más fiable que se llama como lo que buscas",
    "To go back: boot the snapshot from your boot menu (or a live USB), then run  sudo snapper rollback  and reboot.": "Para volver atrás: arranca el snapshot desde el menú de arranque (o un USB live), ejecuta  sudo snapper rollback  y reinicia.",
    "To go back: reboot, open \"Arch Linux snapshots\" in GRUB (grub-btrfs), boot the snapshot and check everything works, then run  sudo snapper rollback  and reboot.": "Para volver atrás: reinicia, abre \"Arch Linux snapshots\" en GRUB (grub-btrfs), arranca el snapshot, comprueba que todo funciona, ejecuta  sudo snapper rollback  y reinicia.",
    "Turn on to get a notification when updates are available (the deck doesn't need to be open).": "Actívalo para recibir un aviso cuando haya actualizaciones (no hace falta tener la app abierta).",
    "UNINSTALL": "DESINSTALAR",
    "UP TO DATE ✓": "AL DÍA ✓",
    "UPDATE ALL": "ACTUALIZAR TODO",
    "UPDATE": "ACTUALIZAR",
    "UPDATES": "ACTUALIZACIONES",
    "UPDATING ": "ACTUALIZANDO ",
    "UPDATING ALL…": "ACTUALIZANDO TODO…",
    "Under 10 votes: few people have checked it": "Menos de 10 votos: poca gente lo ha revisado",
    "Unused Flatpak runtimes": "Runtimes de Flatpak sin usar",
    "Uploaded under 30 days ago with few votes: the usual shape of malicious AUR packages. Read its review carefully.": "Subido hace menos de 30 días y con pocos votos: el perfil típico de los paquetes maliciosos del AUR. Lee bien su revisión.",
    "VERIFIED": "VERIFICADO",
    "WORKING": "TRABAJANDO",
    "Will delete snapshot(s): #": "Se borrarán los snapshots: #",
    "Your snapper config only lets root list snapshots. Load them once with your password, or allow your user to list them (adds you to ALLOW_USERS — reading only; creating still asks for the password).": "Tu configuración de snapper solo deja ver los snapshots a root. Cárgalos una vez con tu contraseña o permite a tu usuario verlos (te añade a ALLOW_USERS, solo lectura; crear sigue pidiendo la contraseña).",
    "\nClick again to confirm.\n": "\nPulsa otra vez para confirmar.\n",
    "\uf108  This update changes the GPU driver (": "\uf108  Esta actualización cambia el driver de la GPU (",
    "app name": "nombre de la app",
    "auto-check off": "comprobación auto off",
    "auto-check on": "comprobación auto on",
    "autostart ": "autoarranque ",
    "available": "disponible",
    "chaotic-aur: AUR packages built by a third party; trust is the AUR package's": "chaotic-aur: paquetes del AUR compilados por un tercero; la confianza es la del paquete del AUR",
    "clean": "limpiar",
    "closed": "cerrado",
    "description for a new snapshot…": "descripción del nuevo snapshot…",
    "edit": "editar",
    "export": "exportar",
    "filter…": "filtrar…",
    "fix": "arreglar",
    "game profile": "perfil de juego",
    "hover a tag to see what it means": "pasa el ratón por una etiqueta para ver qué significa",
    "icon name or /path": "nombre del icono o /ruta",
    "install": "instalar",
    "is OFF (snapper-cleanup.timer disabled)": "está DESACTIVADA (snapper-cleanup.timer desactivado)",
    "launch": "lanzar",
    "load ": "carga ",
    "manual snapshot": "snapshot manual",
    "name": "nombre",
    "not installed": "no instalado",
    "official repos · AUR · Flatpak · GitHub releases": "repos oficiales · AUR · Flatpak · releases de GitHub",
    "open": "abierto",
    "other ": "otros ",
    "path, download URL or github.com/user/repo…": "ruta, URL de descarga o github.com/usuario/repo…",
    "permission ": "permiso ",
    "permission reset": "permisos restablecidos",
    "play": "jugar",
    "repos · AUR · Flatpak · AppImage/GitHub": "repos · AUR · Flatpak · AppImage/GitHub",
    "restore": "restaurar",
    "running": "en marcha",
    "runs hourly": "se ejecuta cada hora",
    "search repos · AUR · flatpak…  or  github.com/user/repo": "busca en repos · AUR · flatpak…  o  github.com/usuario/repo",
    "snap-pac is installed: every pacman operation already gets a pre/post snapshot.": "snap-pac está instalado: cada operación de pacman ya tiene su snapshot pre/post.",
    "snap-pac is not installed: the deck takes a snapshot itself before pacman changes.": "snap-pac no está instalado: la app hace ella misma un snapshot antes de cambios con pacman.",
    "snapper has no '": "snapper no tiene la configuración '",
    "snapshot cleanup": "limpieza de snapshots",
    "snapshot delete": "borrar snapshot",
    "snapshot": "snapshot",
    "snapshots allow": "permitir snapshots",
    "state ": "estado ",
    "uninstall": "desinstalar",
    "update": "actualizar",
    "updated ": "actualizado ",
    "● NEW VERSION": "● NUEVA VERSIÓN",
    "★ RECOMMENDED": "★ RECOMENDADO",
    "✓ AUTO-CHECK ON": "✓ COMPROBACIÓN AUTO ON",
    "✓ AUTOSTART": "✓ INICIO AUTOMÁTICO",
    "✓ DELETE DATA": "✓ BORRAR DATOS",
    "✓ No suspicious patterns found. Still, only build packages you trust.": "✓ No se encontró nada sospechoso. Aun así, compila solo paquetes de confianza.",
};
// sentences with values inside: [regex, replacement]
var PATTERNS = [
    [new RegExp("^(\\d+) SHARPENERS$"), "$1 ENFOQUES"],
    [new RegExp("^(\\d+) EFFECTS$"), "$1 EFECTOS"],
    [new RegExp("^(\\d+) sharpening effects stacked \\((.*)\\): halos and grain\\. One is enough\\.$"), "$1 efectos de nitidez a la vez ($2): halos y grano. Con uno basta."],
    [new RegExp("^(\\d+) sharpener\\(s\\) \\+ (\\d+) local-contrast effect\\(s\\) \\(Clarity…\\): too much detail enhancement, the image gets harsh\\.$"), "$1 de nitidez + $2 de contraste local (Clarity…): demasiado realce de detalle, la imagen queda dura."],
    [new RegExp("^Gamma / colour-space tools \\((.*)\\) are made for one monitor or HDR setup: on another they wash out or darken the picture\\.$"), "Herramientas de gamma / espacio de color ($1): están hechas para un monitor o un HDR concreto; en otro aclaran u oscurecen la imagen."],
    [new RegExp("^(\\d+) colour effects: a strong style of its own, not a fix — very different from the game's look\\.$"), "$1 efectos de color: un estilo fuerte, no una corrección; muy distinto del aspecto del juego."],
    [new RegExp("^Grain / chromatic aberration / vignette \\((.*)\\): a taste, many find them worse\\.$"), "Grano / aberración cromática / viñeta ($1): cuestión de gusto, a mucha gente le parecen peor."],
    [new RegExp("^(.*) read the depth buffer: if you see halos or shading on the UI, turn them off\\.$"), "$1 usan el búfer de profundidad: si ves halos o sombras sobre la interfaz, apágalos."],
    [new RegExp("^not installed: (\\d+) game profile\\(s\\) have GAMEMODE on and it does nothing$"), "no está instalado: $1 perfil(es) de juego tienen GAMEMODE activado y no hace nada"],
    [new RegExp("^Online game with anti-cheat \\((.*)\\): neither is safe there\\.$"), "Juego online con anti-cheat ($1): ninguno es seguro ahí."],
    [new RegExp("^(DirectX 10–12|DirectX 9|OpenGL|A Windows game) under Proton: ReShade itself runs presets exactly as made, depth effects included, with its in-game menu to tweak them\\.$"), "$1 con Proton: ReShade de verdad aplica los presets tal cual, con efectos de profundidad, y tiene su menú en el juego para ajustarlos."],
    [new RegExp("^Your current preset has (\\d+) depth effect\\(s\\) vkBasalt has to skip\\.$"), "Tu preset actual tiene $1 efecto(s) de profundidad que vkBasalt tendría que omitir."],
    [new RegExp("^missing: (.*)$"), "falta: $1"],
    [new RegExp("^loaded(.*)$"), "cargado$1"],
    [new RegExp("^enabled in (.*) \\(32-bit libraries for Steam and Wine\\)$"), "activado en $1 (librerías de 32 bits para Steam y Wine)"],
    [new RegExp("^(.*) present: Proton/Wine can use kernel sync$"), "$1 presente: Proton/Wine pueden usar la sincronización del kernel"],
    [new RegExp("^no NVIDIA, AMD or Intel GPU found in (.*)$"), "no se encontró ninguna GPU NVIDIA, AMD ni Intel en $1"],
    [new RegExp("^install vulkan-tools to check which GPUs Vulkan sees \\(drivers: (.*)\\)$"), "instala vulkan-tools para ver qué GPUs ve Vulkan (drivers: $1)"],
];
